helm:
  parameters:
  - name: frontend.image
    value: ninesun0318/frontend
    forcestring: true
  - name: frontend.tag
    value: main-7613b71
    forcestring: true
  - name: backend.image
    value: ninesun0318/backend
    forcestring: true
  - name: backend.tag
    value: main-7613b71
    forcestring: true
