frontend:
  image: ninesun0318/frontend
  tag: latest
  autoscaling:
    averageUtilization: 90

backend:
  image: ninesun0318/backend
  tag: latest
  autoscaling:
    averageUtilization: 90

database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
